apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  labels:
    app: mongodb
data:
  # Environment variables for MongoDB initialization
  # MONGO_INITDB_ROOT_USERNAME: "admin"
  # MONGO_INITDB_ROOT_PASSWORD: "password123"
  # MONGO_INITDB_DATABASE: "mydatabase"
  mongo-url: "mongo-service"
