apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  labels:
    app: mongodb
type: Opaque
data:
  # Values need to be base64 encoded
  # MONGO_INITDB_ROOT_USERNAME: YWRtaW4=  # base64 for "admin"
  # MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQxMjM=  # base64 for "password123"
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==