apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
  #        volumeMounts:
  #          - name: mongodb-storage
  #            mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
 #     volumes:
 #       - name: mongodb-storage
 #         persistentVolumeClaim:
 #           claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mongodb-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi